
version: 2

models:
  - name: mart__individuals__bmi
    description: Anthropometry of individual pokemon.
    columns:
      - name: pokedex_number
        description: The entry number of the Pokemon in the National Pokedex.
      - name: name
        description: The English name of the Pokemon.
      - name: bmi
        description: The bmi.
        tests:
          - not_null
      - name: weight
        description: The weight.
      - name: height
        description: The height.
